// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC52sa4b5QvcS5dx7oEqi7WqgLWw641X-M',
    appId: '1:489971672202:web:451ca8bdba6c821a2df973',
    messagingSenderId: '489971672202',
    projectId: 'flutterchat922',
    authDomain: 'flutterchat922.firebaseapp.com',
    storageBucket: 'flutterchat922.appspot.com',
    measurementId: 'G-MB624V5RY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm9Epfh0Hggisrvf-pCml-xaNjb4w1auk',
    appId: '1:489971672202:android:2b8d05beaea8f87d2df973',
    messagingSenderId: '489971672202',
    projectId: 'flutterchat922',
    storageBucket: 'flutterchat922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-kq8ZXBaFIORJLVxgfhqWWH5Sap8vwoM',
    appId: '1:489971672202:ios:2a10195d77e98ee52df973',
    messagingSenderId: '489971672202',
    projectId: 'flutterchat922',
    storageBucket: 'flutterchat922.appspot.com',
    iosBundleId: 'co.jp.aimetaversetech.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-kq8ZXBaFIORJLVxgfhqWWH5Sap8vwoM',
    appId: '1:489971672202:ios:7b38bc339d919e4e2df973',
    messagingSenderId: '489971672202',
    projectId: 'flutterchat922',
    storageBucket: 'flutterchat922.appspot.com',
    iosBundleId: 'co.jp.aimetaversetech.flashchat.RunnerTests',
  );
}
